// Generated by CoffeeScript 1.3.3
(function() {
  var onCreate, pluginSupport;

  pluginSupport = null;

  onCreate = function(names, id) {
    var config, name, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = names.length; _i < _len; _i++) {
      name = names[_i];
      config = pluginSupport.definition(name);
      if (config.eager) {
        _results.push(config.factory());
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  Inject.plugin({
    init: function(support) {
      return pluginSupport = support;
    },
    onCreate: onCreate
  });

}).call(this);
