// Generated by CoffeeScript 1.3.3
(function() {

  if (steal.plugins) {
    steal.plugins('jquery', 'jquery/lang')('inject-core.js','controller.js');
  } else {
    steal('jquery', 'jquery/lang', './inject-core.js','./controller.js');
  }

}).call(this);
