// Generated by CoffeeScript 1.3.3
(function() {
  var pluginSupport, resolveWithParent;

  pluginSupport = null;

  resolveWithParent = function(target, name, def) {
    def = pluginSupport.definition('parent-injector-config');
    if (!(def && def.injector)) {
      return;
    }
    return def.injector(name, function(it) {
      return it;
    });
  };

  Inject.plugin({
    init: function(support) {
      return pluginSupport = support;
    },
    factoryMissing: resolveWithParent
  });

}).call(this);
